import { Geist, Geist_Mono, Georama, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/Componnet/Navbar/Navbar";
import Footer from "@/Componnet/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  style: ["normal", "italic"],
});
const georama = Georama({
  variable: "--font-georama",
  subsets: ["latin"],
  
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
     data-theme='light'
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${georama.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-[family-name:var(--font-georama)]" suppressHydrationWarning>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
